### ISSUE TITLE
Missing right parenthesis in Appendix A

### ISSUE THREAD

**Issue by Renovamen** [wangshusen/DRL#10]
老师好，附录 A：贝尔曼方程里这两个地方似乎遗漏了右括号：

![image](https://user-images.githubusercontent.com/29454156/112782831-85cdc200-9080-11eb-9820-8db39905422f.png)
---
![image](https://user-images.githubusercontent.com/29454156/112782870-9bdb8280-9080-11eb-9c18-be095a2aef2a.png)

然后感谢老师的学习资源，辛苦了。

**Comment by wangshusen** [comment]
确实是笔误。非常感谢你的帮助！
