### ISSUE TITLE
4.2.1 一术语使用不妥

### ISSUE THREAD

**Issue by ZJUGuoShuai** [wangshusen/DRL#19]
<img width="1211" alt="截屏2021-06-14 下午2 56 04" src="https://user-images.githubusercontent.com/22856433/121851497-c99ba380-cd20-11eb-9712-3301b5ea39a6.png">
认为在这里使用「平方差」似乎不妥，“平方差”在中文数学里一般意思是“平方的差”，而非“差的平方”。使用“误差平方”或许更合适，或其他的术语。

**Comment by wangshusen** [comment]
你说的没错。我纠正一下。我把你的名字加到致谢里。请问你的名字是郭帅吗？

**Comment by ZJUGuoShuai** [comment]
嗯。
