### ISSUE TITLE
Slides/3_DQN_2.pdf

### ISSUE THREAD

**Issue by null-id** [wangshusen/DRL#2]
https://github.com/wangshusen/DRL/blob/master/Slides/3_DQN_2.pdf

老师您好，请问第30页PPT的selection和evaluation都用target network，跟前一页PPT都用DQN有什么区别呢？

**Comment by wangshusen** [comment]
用target network可以避免Bootstrapping造成的高估。要不你先看一下视频：https://youtu.be/X2-56QN79zc

**Comment by null-id** [comment]
看了视频以后明白了！谢谢老师！
