### ISSUE TITLE
感谢王先生难能可贵的分享，能否给书籍增加书签目录？

### ISSUE THREAD

**Issue by rocke2020** [wangshusen/DRL#36]
如果有了书签目录，我们阅读起来非常方便。能否给书籍增加书签目录？
您可以开通一个赞助的支付或微信账号，我是愿意付费的。谢谢！！
感谢王先生难能可贵的分享！

**Comment by wangshusen** [comment]
Github上当前的版本是有目录的，目录带超链接。你再试试？

**Comment by rocke2020** [comment]
solved
