### ISSUE TITLE
7.3.2 节可能的错误

### ISSUE THREAD

**Issue by aishangcengloua** [wangshusen/DRL#45]
在证明递归公式时，公式(7.3)左边是否应该是 $\boldsymbol{V_\pi (s)}$，而不是 $\boldsymbol{Q_\pi (s, a)}$。但是这样的话与下面又不符，希望老师能够解答一下:dizzy_face:

**Comment by aishangcengloua** [comment]
老师，书籍还没有出版吗？想买一本，电子书看起来不是很自在

**Comment by wangshusen** [comment]
多谢哈。贝尔曼方程有很多种形式。这个公式没错，左边就是 Q。如果再对 a 求期望，那么左边就是 Q。
