### ISSUE TITLE
chapter4: a question about TD

### ISSUE THREAD

**Issue by empty-id** [wangshusen/DRL#5]
Hi professor Wang! I have a question about TD algorithm. You said y hat is a function of parameter w, but TD ignores it and sees it as a constant. What if I don't do like that? Can I just use initial y hat? (Because I think it's still not complex to calculate gradient in that case.)

**Comment by wangshusen** [comment]
Yes, you can, and it will work. You can propagate gradient from y to w. But there must be some empirical reasons why the DRL people don't do that.

**Comment by empty-id** [comment]
Thank you for your reply professor! So what empirical reasons exactly? Training speed, or something else?

**Comment by empty-id** [comment]
Thank you for your reply professor!
