### ISSUE TITLE
Question About P48

### ISSUE THREAD

**Issue by xiaobanni** [wangshusen/DRL#7]
[P56.pdf](https://github.com/wangshusen/DRL/files/6162237/P56.pdf)

您好，请问DRL书本P48页，关于Q学习算法的表格形式的更新公式，红框内的两个更新公式不一样，下面一个是否有误？

**Comment by wangshusen** [comment]
非常感谢！第一个公式是对的，第二个是错的。

**Comment by xiaobanni** [comment]
不客气！教材写的非常好，感谢您的分享！

此外：

P52页应该也是相同的错误。

P111页引理8.2，**b（不）依赖于A**。您可能少打了一个**不**字。

[P52,111.pdf](https://github.com/wangshusen/DRL/files/6164520/P52.111.pdf)

**Comment by wangshusen** [comment]
对，我写错了。再次感谢！如果发现其他错误，还请告知。

**Comment by xiaobanni** [comment]
您好，P108倒数第三行应该为 TD目标 。

![image](https://user-images.githubusercontent.com/33119031/111787145-913f2180-88f9-11eb-8658-67aea6c71a6a.png)

**Comment by wangshusen** [comment]
应该是TD 目标。再次感谢！
